language: c++

compiler:
  - clang
  - gcc

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise
            - kalakris-cmake
        packages:
            - gcc-4.9
            - g++-4.9
            - clang-3.7
            - cmake
            - libtokyocabinet-dev
            - libboost-dev
            - libgmp-dev
            - libxml2-dev
            - zlib1g-dev


before_script: cmake CMakeLists.txt

script:
  - $CXX --version
  - make
